version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    build: .

  redis:
    extends:
      file: common.yml
      service: redis

  redis_second:
    extends:
      file: common.yml
      service: redis

  redis_third:
    extends:
      file: common.yml
      service: redis
